### ISSUE TITLE
"Event" writing in Den Spread

### ISSUE THREAD

**Issue by Real96** [zaksabeast/CaptureSight#11]
Can you add the writing "Event" to spread line if the raid contain an event pokemon? Pkhex shows it with a check box

**Comment by zaksabeast** [comment]
I think having some indication of an event is a good idea, whether it's text or an icon of some sort.

I've also being trying to think of how to handle event Pokemon.  I don't like the idea of releasing a new CaptureSight update every time a new event begins and ends.

Perhaps species shouldn't show for events, and should instead be replaced with an event icon of some sort.

Another thought was to not show a species by default, and have CaptureSight look for a JSON on the SD card with event information.  This would allow the user to keep up to date with events if they wanted to, but it's not required.

If anyone else has any thoughts on this, please chime in.

**Comment by ajbinky** [comment]
I agree, third one seems best to me.

**Comment by zaksabeast** [comment]
I haven't looked into where or when the events are loaded into memory, but that's another option to look into as well.

**Comment by RichardPaulAstley** [comment]
I'll take 100% the 3rd one solution too. Because now we can inject old promotional raids, we should have a way to see the encounter for THAT specific spot. 

And i guess it'd avoid to update CaptureSight every time, just have to push the new files as complement.

**Comment by zaksabeast** [comment]
Marking event dens as "Event" was added with https://github.com/zaksabeast/CaptureSight/commit/c60012ce06fbcf5f3146f7ad15acff2a389326e2.

Reading events from memory was added with https://github.com/zaksabeast/CaptureSight/commit/d4c75c6f75f5a454f764f4da6c4b0fc72afe35fa.
