### ISSUE TITLE
Being able to load old promotional raids / Shiny Magikarp icon

### ISSUE THREAD

**Issue by RichardPaulAstley** [zaksabeast/CaptureSight#12]
Hey ! 

So, as you may know, we can now edit save file in order to inject old promotional raids. It'd be cool to have a way to switch the event settings for Capture Sight. 

That way we could select which kind of promotional raid we want to see for Pokemon in raid list.

Also, would it be possible to have a Shiny Magikarp icon for the Magikarp 2020 event ? It's an encounter slot difference, but could be possible to have a flag on it ?

Thanks <3

**Comment by zaksabeast** [comment]
It looks like there are two parts to this issue:
- Being able to display events on the console accurately
- Shiny sprites

The first point is being discussed on this issue https://github.com/zaksabeast/CaptureSight/issues/11.  It may be worth contributing to the discussion in there.

Adding shiny sprites is a good idea.  If anyone wants to tackle that, it shouldn't be difficult (add shiny sprites and update `getPokemonIconPath`).

**Comment by RichardPaulAstley** [comment]
Oh didn't saw for the first part sorry x_x ! 

About the Shiny Magikarp it's quite linked.
It's not a "classic" Shiny. it was an encounter slot that spawns a Shiny Magikarp.

It works like this for the January 2020 event (for Shield example) : 
G-Max Butterfree / G-Max Corviknight / Shiny Magikarp / G-Max Centiskorch / Magikarp / G-Max Snorlax.

It'd be to make difference between the Magikarp and the Shiny Magikarp.

As a note, an icon or a Shiny Magikarp icon

**Comment by zaksabeast** [comment]
No problem!  Since the intention of this issue is to mark event Pokemon in same way, which is covered in #11, I'm going to close this issue.

Regarding shiny sprites, I still think it's a good idea on its own, and will open a new issue for it.

**Comment by ajbinky** [comment]
> Hey !
> 
> So, as you may know, we can now edit save file in order to inject old promotional raids. It'd be cool to have a way to switch the event settings for Capture Sight.

Is this a feature on pkhex now?
