### ISSUE TITLE
Add shiny sprites

### ISSUE THREAD

**Issue by zaksabeast** [zaksabeast/CaptureSight#13]
Adding shiny sprites is a nice aesthetic touch, and always fun for a Pokemon tool.

If anyone wants to tackle adding shiny sprites, it shouldn't be difficult - add shiny sprites and update `getPokemonIconPath`.

**Comment by ulucs** [comment]
Can you assign this to me? It's a nice addition and I want to learn my way around this UI.

I have a question about build process though. It appears every lib is provided through pacman, so does everyone use Arch to build homebrew? I am installing Arch now, but if there's an Ubuntu workflow I'd much rather use that.

**Comment by zaksabeast** [comment]
Thank you for contributing!

Yep, you can use Ubuntu - that's what I primarily use for building CaptureSight.  devkitPro-pacman has a `deb` package you can download and install on their releases page - https://github.com/devkitPro/pacman/releases/latest

**Comment by ulucs** [comment]
I'm resuming work on this now that kwsch/PKHeX/commit/4c226340fe61b94c590b319108ab68ccec3fcf01 is released

**Comment by zaksabeast** [comment]
Thank you :tada:

**Comment by zaksabeast** [comment]
This has been completed by #32.
