### ISSUE TITLE
Add Abilities to the Pokemon summary screen

### ISSUE THREAD

**Issue by zaksabeast** [zaksabeast/CaptureSight#14]
A requested feature has been to add abilities.  This would be helpful for a number of cases, including breeders who are trying to breed an egg with a specific ability.

If anyone wants to tackle this, here is a good reference commit for how to add and display Pokemon properties - https://github.com/zaksabeast/CaptureSight/commit/8c291a343aa640dd0bc9117f0f5d089baeb5f110.

**Comment by ShinySylveon04** [comment]
I'll be willing to give this a try!

**Comment by zaksabeast** [comment]
Thank you!

**Comment by sleepypikachu** [comment]
Should this issue be closed?

**Comment by zaksabeast** [comment]
Yes, it should
