### ISSUE TITLE
cant run capturesight 

### ISSUE THREAD

**Issue by leozambra** [zaksabeast/CaptureSight#23]
of course i run pokemon sword first(version 1.1) then i try to run capturesight, but i got this message:
PLEASE START A POKEMON GAME before running capturesight  dmnt:cht result: 3328013

**Comment by zaksabeast** [comment]
Are you running any custom sysmodules or using any cheats?

This error seems to come up when something else is using dmnt:cht at the same time CaptureSight tries to use it.

**Comment by leozambra** [comment]
![2020021111220600-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/60856080/74250461-01c04b80-4cc1-11ea-9c51-0ed185ea98ef.jpg)
![2020021111215800-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/60856080/74250469-02f17880-4cc1-11ea-8e4a-716346b4e5d6.jpg)
![2020021111215000-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/60856080/74250470-038a0f00-4cc1-11ea-8bed-0c519f9f764f.jpg)
![2020021111220900-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/60856080/74250471-038a0f00-4cc1-11ea-9bd6-1a25c295e8d2.jpg)



i got all of these installed , but i dont have cheats

**Comment by zaksabeast** [comment]
Are you using Atmosphere, Kosmos, ReiNX, or SX OS?

**Comment by leozambra** [comment]
Atmosphere

**Comment by zaksabeast** [comment]
It looks like Kosmos toolbox is present, which can hotload sysmodules.  Are you using it or any other tool to use custom sysmodules?

**Comment by zaksabeast** [comment]
I'm going to close this due to inactivity.  If you're still having troubles, please let me know :slightly_smiling_face:
