### ISSUE TITLE
New Tesla update causes CS to not show up automatically

### ISSUE THREAD

**Issue by DiscostewSM** [zaksabeast/CaptureSight#29]
With the new firmware update, Atmosphere and Kosmos got updates as well. The latter incorporated Tesla, and has made some changes. Now when entering CaptureSight via overlay, it doesn't automatically show up. It closes Tesla, but technically CS is loaded, so you can go right back into it with the Tesla button combo. Same as when exiting CS.

**Comment by zaksabeast** [comment]
Thanks for the heads up :smile:

**Comment by zaksabeast** [comment]
Fixed with https://github.com/zaksabeast/CaptureSight/commit/cc0cdf1f338add9a728ba1ec0317580ab0bd15b2.
