### ISSUE TITLE
GMAX Milcery Shows Up As Error

### ISSUE THREAD

**Issue by Abu-ZaydAbdullah** [zaksabeast/CaptureSight#30]
![image0](https://user-images.githubusercontent.com/20071707/75848206-1dda7880-5da7-11ea-98fc-12de975bcdeb.jpg)

![mHEfo8](https://user-images.githubusercontent.com/20071707/75848276-5d08c980-5da7-11ea-89fd-ab05e02c2c14.png)

These GMAX Milcery seem to be considered Error Pokemon. They are legit Raid Pokemon and pass legality checks. This is on CaptureSight v4.0 so don't know if this has been patched on master already.

**Comment by zaksabeast** [comment]
Would you be able to send me the pk8 of one of the Pokemon showing up as an error or your save file?  I'm not able to reproduce this and will need more information to find an issue.

**Comment by Abu-ZaydAbdullah** [comment]
Here is the save file.

[main.dms.zip](https://github.com/zaksabeast/CaptureSight/files/4289423/main.dms.zip)

**Comment by zaksabeast** [comment]
Thanks for the save file - that was super helpful!

It looks like the box labeled "Box 1" is actually 5th in your list of boxes:
![pkhex](https://user-images.githubusercontent.com/19464008/76041022-b2afb400-5f16-11ea-9022-a8c208cd6a37.png)

After loading your save up and going to "Box 5" in CaptureSight, I was able to see your Pokemon. :slightly_smiling_face:
