### ISSUE TITLE
Can't see Wild, Raid, and Trade Pokemon

### ISSUE THREAD

**Issue by killemall420** [zaksabeast/CaptureSight#31]
No matter what I do, everything I do with CaptureSight results in an error.
Switch 9.2.0
Atmosphere 0.10.3
CaptureSight 0.4.0
Shield 1.1.0
Here's a screenshot of what I'm experiencing:
![2020030814512400-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/19376407/75917500-15765200-5e28-11ea-9459-84b85c73ee11.jpg)
I have made sure that system_settings.ini has cheats enabled, I've made sure cheats were enabled, I've tried everything. Someone please help me.

**Comment by zaksabeast** [comment]
Hey there!  Thanks for all the info you posted.

Just to make sure I understand, which of these are you having trouble viewing:
- wild Pokemon when in a wild battle
- raid Pokemon when in a raid battle
- trade Pokemon when someone you're trading with shows you a Pokemon to trade

**Comment by zaksabeast** [comment]
Was this issue resolved?

**Comment by zaksabeast** [comment]
I'm closing this since it's stale.  If you are still having problems, please open a new issue.  Thanks!
