### ISSUE TITLE
Possible incorrect information display based on badge count

### ISSUE THREAD

**Issue by SteveCookTU** [zaksabeast/CaptureSight#33]
As we all know, when you gain more badges in-game the level of pokemon and the pokemon you can find in the wilds increases. It seems CaptureSight is displaying incorrect information before completing the game.

Please Note: There is also a chance of interference from sys-botbase but post-story many don't seem to have the issue even with it enabled as a sysmodule.

**Comment by zaksabeast** [comment]
The applet is no longer supported and the overlay shows current data, but does not predict future data.  As a result, this should not be an existing bug.
