### ISSUE TITLE
Black Screen upon updating software.

### ISSUE THREAD

**Issue by christidevito** [zaksabeast/CaptureSight#35]
Hello,

Everytime try to load the app on SXOS i end up with blackscreen. Is it because I updated the game?

Thank you.

**Comment by zaksabeast** [comment]
Hello!

Sorry, SXOS is not supported.  CaptureSight relies heavily on dmnt:cht provided by Atmosphere.

If you'd like to use CaptureSight, please consider using Atmosphere.
