### ISSUE TITLE
Crash after updating

### ISSUE THREAD

**Issue by TheChaotician** [zaksabeast/CaptureSight#38]
Updated to Atmosphere 0.11.1 / Hekate 5.1.4, and OFW 10.0.0.

The Overlay crashes every time i try to load it through Tesla. Tesla seems fine otherwise and runs Luxray with no issues. CaptureSight Applet also works fine.

I have re installed every component multiple times, and have removed all potentially problematic sys-modules.

Any Ideas? I've attached a Crash log to help troubleshoot.
[01587061916_420000000007e51a.log](https://github.com/zaksabeast/CaptureSight/files/4489302/01587061916_420000000007e51a.log)

**Comment by SweetwaterBurns** [comment]
Exact same situation for me. Just upgraded and the overlay stopped working.

**Comment by zaksabeast** [comment]
Thank you for the issue :slightly_smiling_face: 

I've noticed this as well, and will look into the issue some time this weekend.

**Comment by zaksabeast** [comment]
It looks like the overlay uses too much memory on 10.0.0.

I have a fix ready that just needs some testing.  An update will be out today or tomorrow to address this.

**Comment by TheChaotician** [comment]
Great work as usual :)

Thanks for your time!

**Comment by zaksabeast** [comment]
Thank you too!

This has been fixed with https://github.com/zaksabeast/CaptureSight/commit/d42f1ca11af351b43e072b95d4825a7d3395af6b and https://github.com/zaksabeast/CaptureSight/commit/1aa12ed14fa2abeb92c3d4840c11f36b21ee43a0.
