### ISSUE TITLE
Should the overlay box view come back?

### ISSUE THREAD

**Issue by zaksabeast** [zaksabeast/CaptureSight#39]
Most people seem to use the overlay for quickly checking seeds, upcoming shiny frames, and wild/raid stats, but the box view appears to be largely unused in the overlay.  People, including myself, seem to use the applet when viewing box Pokemon with CaptureSight.

The Switch 10.0.0 update broke the overlay as described in #38 due to memory issues.  The method used to populate the box view used a decent amount of memory.  It's definitely possible to show the box view without using nearly as much memory, but if the feature is largely unused in the overlay, it may not be worth implementing.

I'm going to have this discussion thread up for a few days to ask the questions:
- Do you use the box view in the overlay?
- Should the box view come back in the overlay?

**Comment by SweetwaterBurns** [comment]
I've never used the box view in the overlay. The space is kind of cramped so I usually open the applet for a better view.

**Comment by ELY3M** [comment]
I do need to see species in active dens and all dens list.

**Comment by ELY3M** [comment]
I missign seeing what pokemons in the active dens and all dens list in the overlay.

**Comment by zaksabeast** [comment]
I'm going to close this issue since it seems most people don't use the overlay for the box view.

@ELY3M Sorry for the late response - I've been pretty busy and forgot to respond.  Would you be willing to open a new issue with that request so it can be tracked?  Thank you!

**Comment by ELY3M** [comment]
I miss this feature :(

**Comment by ELY3M** [comment]
@zaksabeast
