### ISSUE TITLE
Update for DLC - Most Pokemon Display as "Egg" or "Empty"

### ISSUE THREAD

**Issue by Purebeam** [zaksabeast/CaptureSight#43]
I installed just as explained, and got the same result through using the overlay and the applet.

**Comment by Koi-3088** [comment]
You'll have to wait. Has to be updated for the DLC.

**Comment by zaksabeast** [comment]
Yep, an update for the DLC is being worked on. :slightly_smiling_face: 

While not a hard deadline, I'm hoping to get it out in the next day or two.

**Comment by zaksabeast** [comment]
Closed with the latest release.
