### ISSUE TITLE
Overlay doesn't show eggs in my party

### ISSUE THREAD

**Issue by chimel23** [zaksabeast/CaptureSight#44]
...any idea why? Also, I wish it had a box viewer. I can use the applet mode and have for a while but can you please fix it not showing pokemon in my party properly?

**Comment by zaksabeast** [comment]
Here are a few questions to help troubleshoot the egg issue:
- Can you see the eggs in the applet, but not the overlay?
- Can you see some of the egg's info or none of it?
- Are you using the very latest Sword and Shield update?
- What version of Atmosphere are you using?
- Do these steps fix the issue:
  1. Fully close the overlay by pressing "B" until the CaptureSight overlay and tesla exit
  1. Save the game with eggs in your party
  1. Open the overlay and check whether the eggs are showing correctly

As for the box viewer, I'm not opposed to adding it back to the overlay.  I had [an issue up for several months](https://github.com/zaksabeast/CaptureSight/issues/39) to get community feedback, but it seemed no one cared for the box view in the overlay, so I haven't added it back yet.  If you're interested in this, please open a separate issue for this (it helps me track individual requests if they're separate). If other people show their support for the feature, it prioritizes it for me.

Thanks!

**Comment by zaksabeast** [comment]
@chimel23 Did you get the issue solved?

**Comment by zaksabeast** [comment]
I'm going to close this issue due to inactivity.  If you're still having the problem, please let me know!
