### ISSUE TITLE
Does anyone use the "Upcoming advances" feature?

### ISSUE THREAD

**Issue by zaksabeast** [zaksabeast/CaptureSight#45]
CaptureSight has a way to show the Pokemon of future advances for each den (e.g. advance 1 has a shiny, 2 has an HA Pokemon, 3 has a 6IV, 4 has a shiny 5IV, etc.).

Lots of people prefer to use RaidFinder for this instead since it's much more robust.  CaptureSight offers this feature as a way to be switch-only without the need for a computer, but I'm not sure the feature is used too often.

For anyone wanting a Pokemon with good IVs or a shiny, CaptureSight can accomplish this task without the "Upcoming advances" feature.  For collectors wanting very specific Pokemon, RaidFinder is used due to all its features.

I've been thinking of removing this and wanted to know if anyone uses the "upcoming advances" feature?

(Note: I'm not going to leave this discussion open for too long - just wanted to get a feel for use)

**Comment by Real96** [comment]
Well, it is really useful. Atm it is a bit unconfortable to scroll down/up. But i find it really useful

**Comment by zaksabeast** [comment]
@Real96 How often do you use the "upcoming advances" feature?

Based on the lack of activity so far, and how I don't find much value in the feature, I'm inclined to remove it.

**Comment by Real96** [comment]
Don't worry zak! Also RaidFinder can do the same thing, so this won't be a big lost.

**Comment by zaksabeast** [comment]
I'm closing this issue and removing the "upcoming advances" feature.
