### ISSUE TITLE
Forced shiny raids not showing up correctly

### ISSUE THREAD

**Issue by zaksabeast** [zaksabeast/CaptureSight#46]
I had a report that raid Pokemon forced to be shiny aren't showing up correctly.

This should be a pretty easy fix:
- Update [this field in libcsight](https://github.com/zaksabeast/CaptureSight/blob/master/libcsight/resources/NestHoleDistributionEncounter8Archive.fbs#L36) to be named `ShinyForced` (Thanks to [this line](https://github.com/Leanny/PKHeX_Raid_Plugin/blob/master/PKHeX_Raid_Plugin/Util/NestHoleDistributionEncounter8Archive.cs#L169) in @Leanny's PKHeX raid plugin)
- Follow CaptureSight's [build instructions](https://github.com/zaksabeast/CaptureSight#building) to build a new flatbuffer header
- Add a check [here in Den.cpp](https://github.com/zaksabeast/CaptureSight/blob/master/libcsight/source/csight/Den.cpp#L25) to see if the spawn is forced shiny.  If yes, it will be a square shiny.  If no, calculate as normal

If anyone is interested in taking this on, please let me know!  I'm focused on a different CaptureSight feature for a bit.

**Comment by Leanny** [comment]
Technically it doesnt need to be renamed, does it? I just renamed it to be clear. Pknx for example still uses the old name and also works with it, so might be worth not to rename it

**Comment by zaksabeast** [comment]
You're right that it doesn't need to be renamed, but I think it's good to do for the same reason we try to give any variable a descriptive name.

Good names help make the code more readable for the future, and serves as good documentation for anyone who wants to borrow code.  For example, it was easier to find the named field in your plugin than to read through lots more code to find which field caused specific behaviors.

In my opinion, easier future maintenance (for old and new contributors), better documentation, and the low development cost definitely makes the change valuable.

**Comment by Real96** [comment]
I was just going to open this issue xD

**Comment by Real96** [comment]
You should consider also the case in which the seed gives you a shinable PID but it is forced to be not shiny (maybe you already add this when first Charizard dens where released)

https://github.com/Admiral-Fish/RaidFinder/blob/33ef42f31bab31267f1e15b17b327f089186c13e/Core/Generator/RaidGenerator.cpp#L78

**Comment by zaksabeast** [comment]
This issue should be fixed with https://github.com/zaksabeast/CaptureSight/commit/f8fda119ad261f215b42c0b4dac2bf3f24cd66a3.

@Real96 since you're the one who originally alerted me to the issue, could you please test and make sure it works for you?

**Comment by Real96** [comment]
> This issue should be fixed with [f8fda11](https://github.com/zaksabeast/CaptureSight/commit/f8fda119ad261f215b42c0b4dac2bf3f24cd66a3).
> 
> @Real96 since you're the one who originally alerted me to the issue, could you please test and make sure it works for you?

Yeah sure! There is a case in which the seed shouod generate a star shiny, so pid is forced to square. Did you consider also this case? There is a little pid modification, in the last number of the upper half of it

**Comment by zaksabeast** [comment]
Thanks for testing :slightly_smiling_face: 

> There is a case in which the seed should generate a star shiny, so pid is forced to square. Did you consider also this case?

CaptureSight doesn't actually use/display the final PID of a raid Pokemon, so that's not something I'm super concerned with.  It should still be able to calculate what type of shiny the Pokemon will be, but won't create the final PID of a raid Pokemon based on the shiny type.

`RaidPokemon` does implement a way to get the PID for the `PKM` inheritance, so CaptureSight should either:
- Implement the extra logic for documentation/future use purposes
- Stub out `getPID` (since it's not being used) and leave a comment with an explanation of what the game normally does [here](https://github.com/zaksabeast/CaptureSight/blob/master/libcsight/source/csight/RaidPokemon.cpp#L19)

I'm leaning towards the second option since the extra logic wouldn't benefit CaptureSight in any way and would be more to maintain.

**Comment by Real96** [comment]
> Thanks for testing 
> 
> > There is a case in which the seed should generate a star shiny, so pid is forced to square. Did you consider also this case?
> 
> CaptureSight doesn't actually use/display the final PID of a raid Pokemon, so that's not something I'm super concerned with. It should still be able to calculate what type of shiny the Pokemon will be, but won't create the final PID of a raid Pokemon based on the shiny type.
> 
> `RaidPokemon` does implement a way to get the PID for the `PKM` inheritance, so CaptureSight should either:
> 
> * Implement the extra logic for documentation/future use purposes
> * Stub out `getPID` (since it's not being used) and leave a comment with an explanation of what the game normally does [here](https://github.com/zaksabeast/CaptureSight/blob/master/libcsight/source/csight/RaidPokemon.cpp#L19)
> 
> I'm leaning towards the second option since the extra logic wouldn't benefit CaptureSight in any way and would be more to maintain.

Completely forgot about the PID not being showed!

**Comment by zaksabeast** [comment]
I ended up adding it as part of consolidating shared PKM methods in  https://github.com/zaksabeast/CaptureSight/commit/3c45d34db21f7e437c2aa71fc12be7181fb86847.

**Comment by Real96** [comment]
Going to test it in a 20 min! Sorry for being late >.<

**Comment by Real96** [comment]
Ok i tested it. My actual Zeraora seed is a star seed. But in frames it sasy that next shint frame will be 2347 (Star). I think this has to be changed. All seeds will give you a Square shiny

**Comment by zaksabeast** [comment]
@Real96 Sorry for the late response!  I forgot to mention that I pushed a change for this.  Does it solve the issue?

**Comment by zaksabeast** [comment]
I'm closing this since I believe it was reported to be resolved.
