### ISSUE TITLE
Legend Ram address

### ISSUE THREAD

**Issue by Real96** [zaksabeast/CaptureSight#47]
0x886BC058

Took from here: https://github.com/kwsch/SysBot.NET/blob/a0aff44af3b7fa02900d4099f32e0a9c54801857/SysBot.Pokemon/Structures/RAM/PokeDataOffsets.cs#L36

**Comment by zaksabeast** [comment]
Fixed with https://github.com/zaksabeast/CaptureSight/commit/10ac3a293fb36506b2238f1f79fb8c13d7de4092.  Thanks for opening the issue!
