### ISSUE TITLE
Missing Italian translation

### ISSUE THREAD

**Issue by Real96** [zaksabeast/CaptureSight#48]
![JPEG_20200622_150622](https://user-images.githubusercontent.com/20956021/85864459-d8faa780-b7c4-11ea-9c6b-051aabccfb66.jpg)

Ability filter ---> Filtro abilità
Any ---> Qualsiasi
Regular den ---> Den regolare
Rare den ---> Den raro

**Comment by zaksabeast** [comment]
Thanks for the translations!

Sadly with the applet rewrite, these translations are no longer valid.  I'm going to close this issue in favor of #49 since all translations need updating.
