### ISSUE TITLE
Frame Finder

### ISSUE THREAD

**Issue by n4n0byte** [zaksabeast/CaptureSight#5]
Would you be willing to implement the logic for finding the nearest shiny frame on a per den basis?

**Comment by zaksabeast** [comment]
This is a good idea, and it's certainly possible.

It may take a bit of time before I'm able to implement this, so if anyone else wants to open a PR before I'm able to, I'd be happy to review and merge it.

Thank you for the suggestion!

**Comment by ajbinky** [comment]
Is this in development yet? I would like to help out with this if possible.

**Comment by zaksabeast** [comment]
Hey!   I've been pretty busy lately and haven't started this.  If you'd like to add this feature, that'd be awesome.

Thanks for the interest!

**Comment by ajbinky** [comment]
I wouldn't be able to start until the middle of next week, but I'll definitely look into it!
