### ISSUE TITLE
Request: Show shiny type and alternate forms

### ISSUE THREAD

**Issue by ShinySylveon04** [zaksabeast/CaptureSight#56]
In the Pokemon's summary screen there isn't a field for whether the Pokemon is a Star or Square shiny. Also Pokemon with alternate forms, such as Sinistea, would benefit from displaying which form they are, especially for viewing in raids.

**Comment by zaksabeast** [comment]
Those would be great to have added!

**Comment by zaksabeast** [comment]
These were added with cc948426c928e92370d949144ea11b19a21cc58c and 98cca753ca75e0879f575938b89de9ce5d44fbc9.
