### ISSUE TITLE
Request: "Active Dens" Split Up

### ISSUE THREAD

**Issue by Th3Alic3** [zaksabeast/CaptureSight#57]
Hello!

I personally would like to see the Dens split up in the app. Instead of all the Dens for all 3 areas (base and 2 DLC's), I feel it would help most people if the Den information in Capture Sight was split up:

- Wild Dens (Active)
- Wild Dens (All)
- Isle Dens (Active)
- Isle Dens (All)
- Crown Dens (Active)
- Crown Dens (All)

The first reason is some players (including myself) are typically only focused on a certain Area of Dens during a play session. Especially right now where most players are only focused on Crown Tundra Dens.

The second reason that it would make it faster to check on specific Dens (especially the inactive) if it wasn't one big Giant list. Especially for those using the Overlay applet!

Thanks
(Loving this APP!! You're amazing!!)

**Comment by zaksabeast** [comment]
That sounds like a great improvement - thanks!

**Comment by zaksabeast** [comment]
This has been added in 9cb74cd3995fae0c7482500f613dfcbf99389c38.

**Comment by Th3Alic3** [comment]
Thanks for this!

Will I be seeing a Beta 9.0 or official 9.0 in the next 5 days? _(I really want to do a video highlighting all the new features you are teasing!)_

**Comment by zaksabeast** [comment]
Oh neat, thanks! :slightly_smiling_face:

A new version should be released within the next day or two.  I've had a bit of trouble finding volunteers to help test multiplayer dmax adventures, so there's been a bit of a delay.  The remaining code changes should be finished and ready to go; I'm just waiting for the time this weekend to test a bit more.

**Comment by Th3Alic3** [comment]
*waves* I have time this weekend (I'm out of PST) to be able to offer help.
