### ISSUE TITLE
Zacian / Zamazenta

### ISSUE THREAD

**Issue by Real96** [zaksabeast/CaptureSight#6]
No way to check the Zacian / Zamazenta when you face them (found and reported by Rick in discord)

**Comment by ajbinky** [comment]
Any chance you could post a save file right before the encounter? Also, where can I find a link to the discord?

**Comment by Real96** [comment]
> Any chance you could post a save file right before the encounter? Also, where can I find a link to the discord?

https://www.discord.gg/d8JuAvg

**Comment by zaksabeast** [comment]
Fixed with https://github.com/zaksabeast/CaptureSight/commit/317d0376ad44dd2964c07910ed05052941fa9303.
