### ISSUE TITLE
Request: Dynamax Adventure Shiny PID

### ISSUE THREAD

**Issue by Th3Alic3** [zaksabeast/CaptureSight#62]
Hello Zak'sABeast!!

The new version of Capture Sight is now confirms that the PID values for the 4 rounds of Raid Pokémon are determined prior to the Raids. This means that the PID shown in the Raid viewer as of the newest version is the one the Pokémon will receive when caught by the player using Capture Sight.

For example, here's a Jellicent that I encountered in Round 1:
<img width="729" alt="t1" src="https://user-images.githubusercontent.com/57371173/98493445-514f8b80-21ef-11eb-8762-650cec534ffa.PNG">

Here's the same Jellicent after the Adventure:
![image](https://user-images.githubusercontent.com/57371173/98493562-9bd10800-21ef-11eb-8a66-3d2035c820b0.png)

Which we can see here was assigned the EXACT same PID/EC as previously shown:
![image](https://user-images.githubusercontent.com/57371173/98493612-b60ae600-21ef-11eb-8d62-7fb2e553d2fe.png)

This means that Dynamax Adventure Pokémon will have their Shiny status determined by this known PID value. _(I would love if we could see all 11 mons during Rental selection down the road!!)_

I would like to request that for Future Versions of Capture Sight for the Pokémon Shiny Value (derived from the PID) to be shown in both the applet & overlay for Dynamax Adventure Raids.

The Pokémon Shiny Value (PSV) as scene here in PKHeX:
![image](https://user-images.githubusercontent.com/57371173/98493691-eb173880-21ef-11eb-9fd3-1628b1e81a6d.png)

is compared against a player's own Trainer Shiny Value (TSV) as scene here in PKHeX:
![image](https://user-images.githubusercontent.com/57371173/98494135-0cc4ef80-21f1-11eb-8281-959bdf529c4c.png)

to determine if the Pokémon is Shiny. If the two small numbers are a perfect match, then the Pokémon is Shiny.

This means IF the PSV was added to Capture Sight... Capture Sight would show Shiny-ness for Dynamax Pokémon!!!

**_(The new features are a fantastic addition! Keep up the AMAZING WORK!!)_**

**Comment by zaksabeast** [comment]
SciresM and Kaphotics looked into shininess.  From my understanding, the game checks if the Pokemon should be shiny after the battle using a csprng (so we can't predict the outcome).  If the Pokemon should be shiny, the PID will be modified to make the Pokemon shiny.

Unfortunately this means CaptureSight doesn't have the ability to determine if a Pokemon will be shiny until after the player has already caught the Pokemon.

I appreciate you asking for the feature and putting in the effort to see if the idea was plausible.  Sorry it's not possible though. :slightly_smiling_face:
