### ISSUE TITLE
Report Incorrect Adventure SEED Data: cddb062e825fd49

### ISSUE THREAD

**Issue by Th3Alic3** [zaksabeast/CaptureSight#64]
SEED: cddb062e825fd49
NPCs: 3
Boss: Anything (Kyogre /Listed Type: Water)

Issue: Round 1 / Slot 2 seems to be the only incorrect Pokémon.

![image](https://user-images.githubusercontent.com/57371173/98721023-84a42e80-2345-11eb-903d-642894a70f12.png)
_(I would luv if the number of NPCs was ordered descending vs ascending as I imagine most people aren't going online with Capture Sight.)_

Round 1 & 2 (Capture Sight):
![image](https://user-images.githubusercontent.com/57371173/98722601-1c098180-2346-11eb-970c-e857d530b654.png)

Round 3 (Capture Sight):
![image](https://user-images.githubusercontent.com/57371173/98722705-3c394080-2346-11eb-8c44-c6511987589e.png)
_(The font size could be totally reduced in the app. ;) )_

Round 1/Slot 2 (not a Rotom):
![image](https://user-images.githubusercontent.com/57371173/98720056-43ac1a00-2345-11eb-820c-b91817c1998d.png)

Round 2:
![image](https://user-images.githubusercontent.com/57371173/98722227-e795c580-2345-11eb-9836-f001d0757ce6.png)

Round 3: 
![image](https://user-images.githubusercontent.com/57371173/98722920-86babd00-2346-11eb-9f55-4fe09fb3ce2e.png)

**Comment by Th3Alic3** [comment]
You most likely factored in the version differences but the same as with Raids, the SEEDs are handled slightly different from Sword to Shield.

The SEEDs should produce identical results for all players on Shield or Sword however the result will be different between Sword and Shield.

If you only have it configured for a single version this would explain the differences that I am experience.

**Comment by zaksabeast** [comment]
Just to make sure I'm understanding, are you saying participants using CaptureSight aren't seeing the same results as the host?

**Comment by Th3Alic3** [comment]
Please close this post and refer to: #67
