### ISSUE TITLE
Incompatible with FW 11.0.0

### ISSUE THREAD

**Issue by chasseyblue** [zaksabeast/CaptureSight#65]
Sadly the Overlay and Applet reports all Pokemon as "None". Did function great on 10.2.0.

**Comment by zaksabeast** [comment]
Thank you for reporting this.

**Comment by zaksabeast** [comment]
@chasseyblue I was testing this out, but wasn't able to reproduce it with FW 11.0.0 and the latest Atmosphere.

Would you be able to post a screenshot of your switch showing the current FW it's running (just to be double safe)?  This should also have the Atmosphere version on it.

Could you please also post a screenshot of the Homebrew menu while hovering over CaptureSight to double check the version you have?

And finally, are you running Sword or Shield?

If anyone else is having this issue, feel free to contribute to the conversation as well. :slightly_smiling_face:

**Comment by chasseyblue** [comment]
Hmmm, that's odd. Well as requested here's some screenshots. Apart from the Overlay which doesn't appear to capture. Hopefully it's not just isolated to me 🤪

![IMG_3967](https://user-images.githubusercontent.com/62993343/101890681-21801300-3bf5-11eb-881a-3f729c933669.JPG)

![IMG_3967](https://user-images.githubusercontent.com/62993343/101891027-9e12f180-3bf5-11eb-93e9-db73c0c82d3c.JPG)

![IMG_3965](https://user-images.githubusercontent.com/62993343/101891067-ab2fe080-3bf5-11eb-81f6-657b3e7c1aa7.JPG)

I'm currently using Pokémon Shield.

**Comment by zaksabeast** [comment]
Perfect, thank you for the screenshots.  Over the years I've had several bug reports on other softwares where someone thought they updated something, but accidentally didn't.  As a result, one of my first questions is often to double check versions, just to be safe.

Since everything here checks out, could you please post a screenshot of your Pokemon Shield update version (it should be on the title screen during the opening animation)?

Thanks for baring with me :slightly_smiling_face:

**Comment by chasseyblue** [comment]
I have update patch 5 in Tinfoil and Version 1.3.0 in Home menu.
At the title screen I have no version mentioned at all, however able to go to the DLC worlds, and view DLC Pokémon.

![IMG_3970](https://user-images.githubusercontent.com/62993343/101979130-41bfd880-3cae-11eb-9750-22664c8aff84.JPG)

**Comment by zaksabeast** [comment]
That screenshot shows what I was looking for :slightly_smiling_face: 

This is pretty odd - no one else has reported this, and I'm not able to reproduce it.  If anyone else is having this same issue, please let me know!

@chasseyblue Here are two more questions that might help debug:
- Do you have any custom sysmodules?
- Are you able to load cheats or search the game memory with EdiZon (not even use cheats, just see if EdiZon shows existing cheats)?

**Comment by chasseyblue** [comment]
### Solved!! 😃

**SaltyNX conflicts with CaptureSight.**

Once SaltyNX sysmodule is disabled, and Switch is rebooted. CaptureSight functionality returns.
Thanks for your help @zaksabeast! 

However not sure why this issue occurs as previous FW was fine together with SaltyNX.

**Comment by zaksabeast** [comment]
Awesome!  I'm glad we were able to get this resolved :smile:
