### ISSUE TITLE
Pokemon Sword1.1，not available.

### ISSUE THREAD

**Issue by sylar3814** [zaksabeast/CaptureSight#7]

**Comment by sylar3814** [comment]
1.1 no display

**Comment by zaksabeast** [comment]
Which one of these most accurately describes the issue:
1. Is it showing a black screen
2. Is it showing data, but the data is incorrect
3. Is it not displaying data, but has an error message instead
4. A different issue

If it's number 2, 3, or 4, could you please provide a screenshot?

**Comment by sylar3814** [comment]
2.Data is incorrect






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "zaksabeast"<notifications@github.com&gt;; 
发送时间: 2020年1月10日(星期五) 晚上9:00
收件人: "zaksabeast/CaptureSight"<CaptureSight@noreply.github.com&gt;; 
抄送: "`纨_ぴp"<luokeang@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [zaksabeast/CaptureSight] Pokemon Sword1.1，not available. (#7)




Which one of these most accurately describes the issue:
  
Is it showing a black screen
 
Is it showing data, but the data is incorrect
 
Is it not displaying data, but has an error message instead
 
A different issue
  
If it's number 2, 3, or 4, could you please provide a screenshot?

**Comment by zaksabeast** [comment]
I'm not able to reproduce this.  Could you please provide a screenshot of the issue you're seeing?

**Comment by sylar3814** [comment]
![image](https://user-images.githubusercontent.com/59721132/72259440-6c8f5000-364b-11ea-8e9c-f92b9e7d1282.png)

**Comment by RichardPaulAstley** [comment]
No changes has been done for that.
Except Raid Event, capture Sight works 100% fine with 1.1.0

**Comment by zaksabeast** [comment]
@sylar3814 It looks like you're using the first version of CaptureSight.  Could you please update to the latest release and take a screenshot of the result?

**Comment by aswiftmoose** [comment]
Where do I find the latest release? (is it supposed to be an NRO file?)

**Comment by TGDuran** [comment]
@zaksabeast Trying to check a raid Pokémon and all I see is:
Empty - Wild Pokemon
Empty - Raid Pokemon 
Empty - Trade Pokemon
Worked fine before 1.1.

**Comment by zaksabeast** [comment]
@TGDuran Can you see party Pokemon, box Pokemon, or den info?

> Worked fine before 1.1.

Are you referring to Sword/Sheidl 1.1 or CaptureSight 1.1?

**Comment by TGDuran** [comment]
I can see everything but what’s in Wild and Trade Pokemon. Referring to Sword and Shield 1.1

**Comment by zaksabeast** [comment]
Multiple people have confirmed it's working for them, so there may be a difference with your setup.
- What switch version are you using?
- What version of atmosphere are you using?
- Are you using any cheats?
- Are you using any patches?

**Comment by TGDuran** [comment]
Newest switch firmware, newest atmosphere version, no cheats, newest sword and shield version.

**Comment by TGDuran** [comment]
Switch version 9.1.0
AMS 0.10.2
No cheats
The new Pokémon Shield update

**Comment by ELY3M** [comment]
check if you have system_settings.ini in /atmosphere/config   if you have that file in that dir.  look for this line  dmnt_cheats_enabled_by_default = u8!0x1     make sure it is u8!0x1

**Comment by zaksabeast** [comment]
Just to follow up on this, I just had either the same or related issue where the trade Pokemon wasn't read properly.  I haven't looked into this yet, so I'm not sure what's causing it, especially since the trade view works for most Pokemon, but it looks like CaptureSight was reading a garbage Pokemon.

My first thought is the offset being used to read trade Pokemon isn't always correct, and should be changed to a different location.

**Comment by sylar3814** [comment]
ok,Opened the tv model,**thanks.!**

**Comment by Heartbeat-Heartbreak** [comment]
> Just to follow up on this, I just had either the same or related issue where the trade Pokemon wasn't read properly. I haven't looked into this yet, so I'm not sure what's causing it, especially since the trade view works for most Pokemon, but it looks like CaptureSight was reading a garbage Pokemon.
> 
> My first thought is the offset being used to read trade Pokemon isn't always correct, and should be changed to a different location.

hey guys, I have the same problems, I use Tesla ovl and homebrew, but all  data is empty. and then I disable the ReverseNX, it works. It looks like your plugin conflicts with ReverseNX?
switch FW：9.1
atmosphere：0.10.2
game version：shield 1.1
Poor English, hope it can help you

**Comment by zaksabeast** [comment]
Possibly - I haven't heard of ReverseNX, so I can't speak to it.  There are some sysmodules that do conflict with CaptureSight, so I wouldn't be surprised.

**Comment by zaksabeast** [comment]
Just a thought - what is everyone's Switch language set to?

Some of the memory offsets change based on language.

**Comment by zaksabeast** [comment]
I'm going to close this due to:
- Inactivity
- The original poster got their issue solved

@TGDuran - your issue looks slightly different than the original poster's, more closely relating to this issue: https://github.com/zaksabeast/CaptureSight/issues/31

If you're still having having troubles or want to contribute to that conversation, you're welcome to join there. :slightly_smiling_face:
