### ISSUE TITLE
CaptureSight Skips Shinies

### ISSUE THREAD

**Issue by cDOTwav** [zaksabeast/CaptureSight#76]
Whenever I try and do the time skip glitch to get to the shiny pokemon, instead of getting to it, it just skips to the next available shiny in that den. So for example I'm trying to get a shiny seismitoad and it was about 150 frames away, and as I'm doing it I notice it keeps switching the pokemon instead of saying it was a shiny seismitoad. I finally get to 1 and when I do the time skip glitch it skips over to maybe drednaw. I'm on firmware 13.0.1 and running CaptureSight version 0.10.0 I believe.

**Comment by zaksabeast** [comment]
CaptureSight isn't skipping shinies, it's just reading information.  It sounds like this isn't a CaptureSight issue, but troubles doing the RNG.

If you're having trouble doing the RNG you can:
 - [Follow this RNG guide](https://www.pokemonrng.com/retail-swsh-raid)
 - Ask for help on the Pokemon RNG discord
 - Ask for help on the Pokemon Max Raids discord
 - Ask for help on the pokemonmaxraids subreddit
 - Ask for help on the pokemonrng subreddit
