### ISSUE TITLE
Den 16 : Hidden Den.

### ISSUE THREAD

**Issue by RichardPaulAstley** [zaksabeast/CaptureSight#8]
As i've reported you in DMs a few days ago, CaptureSight ignores and display the Den 16 (the Ghost type one)

The issue may be related to the crystal den ID.

**Comment by zaksabeast** [comment]
Fixed with https://github.com/zaksabeast/CaptureSight/commit/e66dcc0d27883c955c7a4fae46988be8fe2f882a.
