### ISSUE TITLE
Crash when gdbstub is open

### ISSUE THREAD

**Issue by ca1e** [zaksabeast/CaptureSight#83]
experimental support for Atmosphère's gdbstub is available since Atmosphère 1.2.3
atmosphere!enable_standalone_gdbstub = u8!0x1 in system_settings.ini

**Comment by zaksabeast** [comment]
It's not currently possible to use use dmnt:cht when gdb is enabled, and CaptureSight relies on dmnt:cht.

As Atmosphere is updated with new features that will work with gdb and gdb support is no longer experimental, CaptureSight will update accordingly.  For now, this isn't something CaptureSight can fix.
