### ISSUE TITLE
CaptureSight not detecting any info in Shield

### ISSUE THREAD

**Issue by Doddy885** [zaksabeast/CaptureSight#96]
Started encountering this problem a while ago for no reason. Tried updating it just now to try and fix it but still doesn't work.

The issue is pretty much as the title says - CaptureSight isn't detecting or displaying any information form the game in Pokemon Shield. I've made sure Shield, CS and Tesla overlay are up to date as of writing this. I can't see any active dens, no info on party or wild pokemon, just generally no information.

**Comment by ChrisCrashX** [comment]
Idk if you ever found a fix, but I am also having this issue with both sword and shield, can anyone please help?

**Comment by zaksabeast** [comment]
Someone else fixed it by uninstalling mods: https://github.com/zaksabeast/CaptureSight/issues/103#issuecomment-1913850625.  If anyone else runs into this, make sure you don't have mods installed.
